name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]

    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
        pip install -e . --no-deps
#    - name: Lint with flake8
#      run: flake8 roocs_utils tests
#      if: matrix.python-version == 3.6
#    - name: Check formatting with black
#      run: black --check --target-version py36 roocs_utils tests
#      if: matrix.python-version == 3.6
    - name: Test with pytest
      run: |
        python -m pytest -v tests
